-- liquibase formatted sql

-- changeset tuszy:1708603737704-1
CREATE TABLE refresh_token
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token        VARCHAR(255),
    created_date TIMESTAMP,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

-- changeset tuszy:1708603737704-2
CREATE TABLE token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    user_id     BIGINT,
    expiry_date TIMESTAMP,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

-- changeset tuszy:1708603737704-3
ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

