-- liquibase formatted sql

-- changeset tuszy:1
CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-2
CREATE TABLE category_listings
(
    category_id BIGINT NOT NULL,
    listings_id BIGINT NOT NULL
);

-- changeset tuszy:1708602886477-3
CREATE TABLE game
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_game PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-4
CREATE TABLE game_categories
(
    game_id       BIGINT NOT NULL,
    categories_id BIGINT NOT NULL
);

-- changeset tuszy:1708602886477-5
CREATE TABLE item
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255),
    tags                   VARCHAR(255),
    price_and_date_history VARCHAR(255),
    steam_market_id        INT                                     NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-6
CREATE TABLE item_photo
(
    item_id  BIGINT NOT NULL,
    photo_id BIGINT NOT NULL
);

-- changeset tuszy:1708602886477-7
CREATE TABLE listing
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_entity_id BIGINT,
    item_id        BIGINT,
    created_date   TIMESTAMP,
    price          DOUBLE PRECISION                        NOT NULL,
    description    VARCHAR(255),
    title          VARCHAR(255),
    is_for_trade   BOOLEAN                                 NOT NULL,
    is_for_sale    BOOLEAN                                 NOT NULL,
    is_negotiable  BOOLEAN                                 NOT NULL,
    amount         INT                                     NOT NULL,
    is_quick_buy   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_listing PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-8
CREATE TABLE photo
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_path VARCHAR(255),
    name      VARCHAR(255),
    item_id   BIGINT,
    CONSTRAINT pk_photo PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-9
CREATE TABLE rating
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating            INT                                     NOT NULL,
    opinion_message   VARCHAR(255),
    rating_giver_id   BIGINT,
    rating_reciver_id BIGINT,
    CONSTRAINT pk_rating PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-10
CREATE TABLE report
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reported_by_user_entity_id BIGINT                                  NOT NULL,
    reported_user_entity_id    BIGINT                                  NOT NULL,
    message                    VARCHAR(255),
    cause                      VARCHAR(255),
    CONSTRAINT pk_report PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-11
CREATE TABLE top_up
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date           TIMESTAMP,
    user_entity_id BIGINT                                  NOT NULL,
    amount         DOUBLE PRECISION                        NOT NULL,
    payment_option VARCHAR(255),
    CONSTRAINT pk_topup PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-12
CREATE TABLE transaction
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_entity1_id         BIGINT,
    user_entity2_id         BIGINT,
    date                    TIMESTAMP,
    is_trade                BOOLEAN                                 NOT NULL,
    is_monetary_transaction BOOLEAN                                 NOT NULL,
    is_user_entity1bot      BOOLEAN                                 NOT NULL,
    is_user_entity2bot      BOOLEAN                                 NOT NULL,
    chat                    BLOB,
    payment_used            VARCHAR(255),
    transaction_status      VARCHAR(255),
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-13
CREATE TABLE transaction_user_entity1items
(
    transaction_id       BIGINT NOT NULL,
    user_entity1items_id BIGINT NOT NULL
);

-- changeset tuszy:1708602886477-14
CREATE TABLE transaction_user_entity2items
(
    transaction_id       BIGINT NOT NULL,
    user_entity2items_id BIGINT NOT NULL
);

-- changeset tuszy:1708602886477-15
CREATE TABLE user_entity
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                   VARCHAR(255),
    email                      VARCHAR(255),
    password                   VARCHAR(255),
    phone_number               VARCHAR(255),
    balance                    DOUBLE PRECISION                        NOT NULL,
    name                       VARCHAR(255),
    surename                   VARCHAR(255),
    created_date               TIMESTAMP,
    current_fee_flat           DOUBLE PRECISION                        NOT NULL,
    current_fee_percentage     DOUBLE PRECISION                        NOT NULL,
    level                      INT                                     NOT NULL,
    role                       VARCHAR(255),
    is_account_expired         BOOLEAN                                 NOT NULL,
    is_locked                  BOOLEAN                                 NOT NULL,
    is_credentials_non_expired BOOLEAN                                 NOT NULL,
    is_enabled                 BOOLEAN                                 NOT NULL,
    perviously_used_passwords  VARCHAR(255),
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

-- changeset tuszy:1708602886477-16
CREATE TABLE user_entity_reports_recived
(
    user_entity_id     BIGINT NOT NULL,
    reports_recived_id BIGINT NOT NULL
);

-- changeset tuszy:1708602886477-17
ALTER TABLE category_listings
    ADD CONSTRAINT uc_category_listings_listings UNIQUE (listings_id);

-- changeset tuszy:1708602886477-18
ALTER TABLE game_categories
    ADD CONSTRAINT uc_game_categories_categories UNIQUE (categories_id);

-- changeset tuszy:1708602886477-19
ALTER TABLE item_photo
    ADD CONSTRAINT uc_item_photo_photo UNIQUE (photo_id);

-- changeset tuszy:1708602886477-20
ALTER TABLE report
    ADD CONSTRAINT uc_report_reportedbyuserentity UNIQUE (reported_by_user_entity_id);

-- changeset tuszy:1708602886477-21
ALTER TABLE report
    ADD CONSTRAINT uc_report_reporteduserentity UNIQUE (reported_user_entity_id);

-- changeset tuszy:1708602886477-22
ALTER TABLE top_up
    ADD CONSTRAINT uc_topup_userentity UNIQUE (user_entity_id);

-- changeset tuszy:1708602886477-23
ALTER TABLE transaction_user_entity1items
    ADD CONSTRAINT uc_transaction_user_entity1items_userentity1items UNIQUE (user_entity1items_id);

-- changeset tuszy:1708602886477-24
ALTER TABLE transaction_user_entity2items
    ADD CONSTRAINT uc_transaction_user_entity2items_userentity2items UNIQUE (user_entity2items_id);

-- changeset tuszy:1708602886477-25
ALTER TABLE user_entity_reports_recived
    ADD CONSTRAINT uc_user_entity_reports_recived_reportsrecived UNIQUE (reports_recived_id);

-- changeset tuszy:1708602886477-26
ALTER TABLE listing
    ADD CONSTRAINT FK_LISTING_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

-- changeset tuszy:1708602886477-27
ALTER TABLE listing
    ADD CONSTRAINT FK_LISTING_ON_USER_ENTITY FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset tuszy:1708602886477-28
ALTER TABLE photo
    ADD CONSTRAINT FK_PHOTO_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

-- changeset tuszy:1708602886477-29
ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_RATING_GIVER FOREIGN KEY (rating_giver_id) REFERENCES user_entity (id);

-- changeset tuszy:1708602886477-30
ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_RATING_RECIVER FOREIGN KEY (rating_reciver_id) REFERENCES user_entity (id);

-- changeset tuszy:1708602886477-31
ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_REPORTEDBYUSERENTITY FOREIGN KEY (reported_by_user_entity_id) REFERENCES user_entity (id);

-- changeset tuszy:1708602886477-32
ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_REPORTEDUSERENTITY FOREIGN KEY (reported_user_entity_id) REFERENCES user_entity (id);

-- changeset tuszy:1708602886477-33
ALTER TABLE top_up
    ADD CONSTRAINT FK_TOPUP_ON_USERENTITY FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset tuszy:1708602886477-34
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER_ENTITY1 FOREIGN KEY (user_entity1_id) REFERENCES user_entity (id);

-- changeset tuszy:1708602886477-35
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER_ENTITY2 FOREIGN KEY (user_entity2_id) REFERENCES user_entity (id);

-- changeset tuszy:1708602886477-36
ALTER TABLE category_listings
    ADD CONSTRAINT fk_catlis_on_category FOREIGN KEY (category_id) REFERENCES category (id);

-- changeset tuszy:1708602886477-37
ALTER TABLE category_listings
    ADD CONSTRAINT fk_catlis_on_listing FOREIGN KEY (listings_id) REFERENCES listing (id);

-- changeset tuszy:1708602886477-38
ALTER TABLE game_categories
    ADD CONSTRAINT fk_gamcat_on_category FOREIGN KEY (categories_id) REFERENCES category (id);

-- changeset tuszy:1708602886477-39
ALTER TABLE game_categories
    ADD CONSTRAINT fk_gamcat_on_game FOREIGN KEY (game_id) REFERENCES game (id);

-- changeset tuszy:1708602886477-40
ALTER TABLE item_photo
    ADD CONSTRAINT fk_itepho_on_item FOREIGN KEY (item_id) REFERENCES item (id);

-- changeset tuszy:1708602886477-41
ALTER TABLE item_photo
    ADD CONSTRAINT fk_itepho_on_photo FOREIGN KEY (photo_id) REFERENCES photo (id);

-- changeset tuszy:1708602886477-42
ALTER TABLE transaction_user_entity1items
    ADD CONSTRAINT fk_trauseent_on_item FOREIGN KEY (user_entity1items_id) REFERENCES item (id);

-- changeset tuszy:1708602886477-43
ALTER TABLE transaction_user_entity2items
    ADD CONSTRAINT fk_trauseent_on_itemndz99w FOREIGN KEY (user_entity2items_id) REFERENCES item (id);

-- changeset tuszy:1708602886477-44
ALTER TABLE transaction_user_entity1items
    ADD CONSTRAINT fk_trauseent_on_transaction FOREIGN KEY (transaction_id) REFERENCES transaction (id);

-- changeset tuszy:1708602886477-45
ALTER TABLE transaction_user_entity2items
    ADD CONSTRAINT fk_trauseent_on_transactionW3tsOs FOREIGN KEY (transaction_id) REFERENCES transaction (id);

-- changeset tuszy:1708602886477-46
ALTER TABLE user_entity_reports_recived
    ADD CONSTRAINT fk_useentreprec_on_report FOREIGN KEY (reports_recived_id) REFERENCES report (id);

-- changeset tuszy:1708602886477-47
ALTER TABLE user_entity_reports_recived
    ADD CONSTRAINT fk_useentreprec_on_user_entity FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

