-- liquibase formatted sql

-- changeset michaltu:1708687357575-1
CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-2
CREATE TABLE category_listings
(
    category_id BIGINT NOT NULL,
    listings_id BIGINT NOT NULL
);

-- changeset michaltu:1708687357575-3
CREATE TABLE game
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_game PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-4
CREATE TABLE game_categories
(
    game_id       BIGINT NOT NULL,
    categories_id BIGINT NOT NULL
);

-- changeset michaltu:1708687357575-5
CREATE TABLE item
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255),
    tags                   VARCHAR(255),
    price_and_date_history VARCHAR(255),
    steam_market_id        INT                                     NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-6
CREATE TABLE item_photo
(
    item_id  BIGINT NOT NULL,
    photo_id BIGINT NOT NULL
);

-- changeset michaltu:1708687357575-7
CREATE TABLE listing
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_entity_id BIGINT,
    item_id        BIGINT,
    created_date   TIMESTAMP,
    price          DOUBLE PRECISION                        NOT NULL,
    description    VARCHAR(255),
    title          VARCHAR(255),
    is_for_trade   BOOLEAN                                 NOT NULL,
    is_for_sale    BOOLEAN                                 NOT NULL,
    is_negotiable  BOOLEAN                                 NOT NULL,
    amount         INT                                     NOT NULL,
    is_quick_buy   BOOLEAN                                 NOT NULL,
    views          INT                                     NOT NULL,
    is_promoted    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_listing PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-8
CREATE TABLE photo
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_path VARCHAR(255),
    name      VARCHAR(255),
    item_id   BIGINT,
    CONSTRAINT pk_photo PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-9
CREATE TABLE rating
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating            INT                                     NOT NULL,
    opinion_message   VARCHAR(255),
    rating_giver_id   BIGINT,
    rating_reciver_id BIGINT,
    CONSTRAINT pk_rating PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-10
CREATE TABLE refresh_token
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token        VARCHAR(255),
    created_date TIMESTAMP,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-11
CREATE TABLE report
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reported_by_user_entity_id BIGINT                                  NOT NULL,
    reported_user_entity_id    BIGINT                                  NOT NULL,
    message                    VARCHAR(255),
    cause                      VARCHAR(255),
    CONSTRAINT pk_report PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-12
CREATE TABLE token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    user_id     BIGINT,
    expiry_date TIMESTAMP,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-13
CREATE TABLE top_up
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date           TIMESTAMP,
    user_entity_id BIGINT                                  NOT NULL,
    amount         DOUBLE PRECISION                        NOT NULL,
    payment_option VARCHAR(255),
    CONSTRAINT pk_topup PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-14
CREATE TABLE transaction
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_entity1_id         BIGINT,
    user_entity2_id         BIGINT,
    date                    TIMESTAMP,
    is_trade                BOOLEAN                                 NOT NULL,
    is_monetary_transaction BOOLEAN                                 NOT NULL,
    is_user_entity1bot      BOOLEAN                                 NOT NULL,
    is_user_entity2bot      BOOLEAN                                 NOT NULL,
    chat                    BLOB,
    payment_used            VARCHAR(255),
    transaction_status      VARCHAR(255),
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-15
CREATE TABLE transaction_user_entity1items
(
    transaction_id       BIGINT NOT NULL,
    user_entity1items_id BIGINT NOT NULL
);

-- changeset michaltu:1708687357575-16
CREATE TABLE transaction_user_entity2items
(
    transaction_id       BIGINT NOT NULL,
    user_entity2items_id BIGINT NOT NULL
);

-- changeset michaltu:1708687357575-17
CREATE TABLE user_entity
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                   VARCHAR(255),
    email                      VARCHAR(255),
    password                   VARCHAR(255),
    phone_number               VARCHAR(255),
    balance                    DOUBLE PRECISION                        NOT NULL,
    name                       VARCHAR(255),
    surename                   VARCHAR(255),
    created_date               TIMESTAMP,
    current_fee_flat           DOUBLE PRECISION                        NOT NULL,
    current_fee_percentage     DOUBLE PRECISION                        NOT NULL,
    level                      INT                                     NOT NULL,
    role                       VARCHAR(255),
    is_account_expired         BOOLEAN                                 NOT NULL,
    is_locked                  BOOLEAN                                 NOT NULL,
    is_credentials_non_expired BOOLEAN                                 NOT NULL,
    is_enabled                 BOOLEAN                                 NOT NULL,
    perviously_used_passwords  VARCHAR(255),
    profile_picture_id         BIGINT,
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

-- changeset michaltu:1708687357575-18
CREATE TABLE user_entity_ratings_recived
(
    user_entity_id     BIGINT NOT NULL,
    ratings_recived_id BIGINT NOT NULL
);

-- changeset michaltu:1708687357575-19
CREATE TABLE user_entity_reports_recived
(
    user_entity_id     BIGINT NOT NULL,
    reports_recived_id BIGINT NOT NULL
);

-- changeset michaltu:1708687357575-20
CREATE TABLE user_entity_transactions
(
    user_entity_id  BIGINT NOT NULL,
    transactions_id BIGINT NOT NULL
);

-- changeset michaltu:1708687357575-21
ALTER TABLE category_listings
    ADD CONSTRAINT uc_category_listings_listings UNIQUE (listings_id);

-- changeset michaltu:1708687357575-22
ALTER TABLE game_categories
    ADD CONSTRAINT uc_game_categories_categories UNIQUE (categories_id);

-- changeset michaltu:1708687357575-23
ALTER TABLE item_photo
    ADD CONSTRAINT uc_item_photo_photo UNIQUE (photo_id);

-- changeset michaltu:1708687357575-24
ALTER TABLE report
    ADD CONSTRAINT uc_report_reportedbyuserentity UNIQUE (reported_by_user_entity_id);

-- changeset michaltu:1708687357575-25
ALTER TABLE report
    ADD CONSTRAINT uc_report_reporteduserentity UNIQUE (reported_user_entity_id);

-- changeset michaltu:1708687357575-26
ALTER TABLE top_up
    ADD CONSTRAINT uc_topup_userentity UNIQUE (user_entity_id);

-- changeset michaltu:1708687357575-27
ALTER TABLE transaction_user_entity1items
    ADD CONSTRAINT uc_transaction_user_entity1items_userentity1items UNIQUE (user_entity1items_id);

-- changeset michaltu:1708687357575-28
ALTER TABLE transaction_user_entity2items
    ADD CONSTRAINT uc_transaction_user_entity2items_userentity2items UNIQUE (user_entity2items_id);

-- changeset michaltu:1708687357575-29
ALTER TABLE user_entity_ratings_recived
    ADD CONSTRAINT uc_user_entity_ratings_recived_ratingsrecived UNIQUE (ratings_recived_id);

-- changeset michaltu:1708687357575-30
ALTER TABLE user_entity_reports_recived
    ADD CONSTRAINT uc_user_entity_reports_recived_reportsrecived UNIQUE (reports_recived_id);

-- changeset michaltu:1708687357575-31
ALTER TABLE user_entity_transactions
    ADD CONSTRAINT uc_user_entity_transactions_transactions UNIQUE (transactions_id);

-- changeset michaltu:1708687357575-32
ALTER TABLE listing
    ADD CONSTRAINT FK_LISTING_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

-- changeset michaltu:1708687357575-33
ALTER TABLE listing
    ADD CONSTRAINT FK_LISTING_ON_USER_ENTITY FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-34
ALTER TABLE photo
    ADD CONSTRAINT FK_PHOTO_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

-- changeset michaltu:1708687357575-35
ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_RATING_GIVER FOREIGN KEY (rating_giver_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-36
ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_RATING_RECIVER FOREIGN KEY (rating_reciver_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-37
ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_REPORTEDBYUSERENTITY FOREIGN KEY (reported_by_user_entity_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-38
ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_REPORTEDUSERENTITY FOREIGN KEY (reported_user_entity_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-39
ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-40
ALTER TABLE top_up
    ADD CONSTRAINT FK_TOPUP_ON_USERENTITY FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-41
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER_ENTITY1 FOREIGN KEY (user_entity1_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-42
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER_ENTITY2 FOREIGN KEY (user_entity2_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-43
ALTER TABLE user_entity
    ADD CONSTRAINT FK_USERENTITY_ON_PROFILE_PICTURE FOREIGN KEY (profile_picture_id) REFERENCES photo (id);

-- changeset michaltu:1708687357575-44
ALTER TABLE category_listings
    ADD CONSTRAINT fk_catlis_on_category FOREIGN KEY (category_id) REFERENCES category (id);

-- changeset michaltu:1708687357575-45
ALTER TABLE category_listings
    ADD CONSTRAINT fk_catlis_on_listing FOREIGN KEY (listings_id) REFERENCES listing (id);

-- changeset michaltu:1708687357575-46
ALTER TABLE game_categories
    ADD CONSTRAINT fk_gamcat_on_category FOREIGN KEY (categories_id) REFERENCES category (id);

-- changeset michaltu:1708687357575-47
ALTER TABLE game_categories
    ADD CONSTRAINT fk_gamcat_on_game FOREIGN KEY (game_id) REFERENCES game (id);

-- changeset michaltu:1708687357575-48
ALTER TABLE item_photo
    ADD CONSTRAINT fk_itepho_on_item FOREIGN KEY (item_id) REFERENCES item (id);

-- changeset michaltu:1708687357575-49
ALTER TABLE item_photo
    ADD CONSTRAINT fk_itepho_on_photo FOREIGN KEY (photo_id) REFERENCES photo (id);

-- changeset michaltu:1708687357575-50
ALTER TABLE transaction_user_entity1items
    ADD CONSTRAINT fk_trauseent_on_item FOREIGN KEY (user_entity1items_id) REFERENCES item (id);

-- changeset michaltu:1708687357575-51
ALTER TABLE transaction_user_entity2items
    ADD CONSTRAINT fk_trauseent_on_itemuI7yeD FOREIGN KEY (user_entity2items_id) REFERENCES item (id);

-- changeset michaltu:1708687357575-52
ALTER TABLE transaction_user_entity1items
    ADD CONSTRAINT fk_trauseent_on_transaction FOREIGN KEY (transaction_id) REFERENCES transaction (id);

-- changeset michaltu:1708687357575-53
ALTER TABLE transaction_user_entity2items
    ADD CONSTRAINT fk_trauseent_on_transactionmlJi9L FOREIGN KEY (transaction_id) REFERENCES transaction (id);

-- changeset michaltu:1708687357575-54
ALTER TABLE user_entity_ratings_recived
    ADD CONSTRAINT fk_useentratrec_on_rating FOREIGN KEY (ratings_recived_id) REFERENCES rating (id);

-- changeset michaltu:1708687357575-55
ALTER TABLE user_entity_ratings_recived
    ADD CONSTRAINT fk_useentratrec_on_user_entity FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-56
ALTER TABLE user_entity_reports_recived
    ADD CONSTRAINT fk_useentreprec_on_report FOREIGN KEY (reports_recived_id) REFERENCES report (id);

-- changeset michaltu:1708687357575-57
ALTER TABLE user_entity_reports_recived
    ADD CONSTRAINT fk_useentreprec_on_user_entity FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset michaltu:1708687357575-58
ALTER TABLE user_entity_transactions
    ADD CONSTRAINT fk_useenttra_on_transaction FOREIGN KEY (transactions_id) REFERENCES transaction (id);

-- changeset michaltu:1708687357575-59
ALTER TABLE user_entity_transactions
    ADD CONSTRAINT fk_useenttra_on_user_entity FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

