-- liquibase formatted sql

-- changeset micha:1713372866418-3
ALTER TABLE TOKEN DROP CONSTRAINT FK_TOKEN_ON_USER;

-- changeset micha:1713372866418-1
CREATE TABLE verification_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    user_id     BIGINT,
    expiry_date TIMESTAMP,
    CONSTRAINT pk_verificationtoken PRIMARY KEY (id)
);

-- changeset micha:1713372866418-2
ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFICATIONTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset micha:1713372866418-4
DROP TABLE TOKEN CASCADE;

