-- liquibase formatted sql

-- changeset michaltu:1715314131181-1
CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-3
CREATE TABLE game
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_game PRIMARY KEY (id)
);


-- changeset michaltu:1715314131181-5
CREATE TABLE item
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255),
    tags                   VARCHAR(255),
    price_and_date_history VARCHAR(255),
    steam_market_id        INT                                     NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);


-- changeset michaltu:1715314131181-7
CREATE TABLE listing
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_entity_id BIGINT,
    item_id        BIGINT,
    created_date   TIMESTAMP,
    price          DOUBLE PRECISION                        NOT NULL,
    description    VARCHAR(255),
    title          VARCHAR(255),
    is_for_trade   BOOLEAN                                 NOT NULL,
    is_for_sale    BOOLEAN                                 NOT NULL,
    is_negotiable  BOOLEAN                                 NOT NULL,
    amount         INT                                     NOT NULL,
    is_quick_buy   BOOLEAN                                 NOT NULL,
    views          INT                                     NOT NULL,
    is_promoted    BOOLEAN                                 NOT NULL,
    url            VARCHAR(255),
    CONSTRAINT pk_listing PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-8
CREATE TABLE photo
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_path VARCHAR(255),
    name      VARCHAR(255),
    item_id   BIGINT,
    CONSTRAINT pk_photo PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-9
CREATE TABLE rating
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating             INT                                     NOT NULL,
    opinion_message    VARCHAR(255),
    rating_giver_id    BIGINT,
    rating_receiver_id BIGINT,
    CONSTRAINT pk_rating PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-10
CREATE TABLE refresh_token
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token        VARCHAR(255),
    created_date TIMESTAMP,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-11
CREATE TABLE report
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reported_by_id   BIGINT                                  NOT NULL,
    reported_user_id BIGINT                                  NOT NULL,
    message          VARCHAR(255),
    cause            VARCHAR(255),
    CONSTRAINT pk_report PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-12
CREATE TABLE top_up
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date           TIMESTAMP,
    user_entity_id BIGINT                                  NOT NULL,
    amount         DOUBLE PRECISION                        NOT NULL,
    payment_option VARCHAR(255),
    CONSTRAINT pk_topup PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-13
CREATE TABLE transaction
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_entity1_id         BIGINT,
    user_entity2_id         BIGINT,
    date                    TIMESTAMP,
    is_trade                BOOLEAN                                 NOT NULL,
    is_monetary_transaction BOOLEAN                                 NOT NULL,
    is_user_entity1bot      BOOLEAN                                 NOT NULL,
    is_user_entity2bot      BOOLEAN                                 NOT NULL,
    chat                    BLOB,
    payment_used            VARCHAR(255),
    transaction_status      VARCHAR(255),
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-16
CREATE TABLE user_entity
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                   VARCHAR(255),
    email                      VARCHAR(255),
    password                   VARCHAR(255),
    phone_number               VARCHAR(255),
    balance                    DOUBLE PRECISION                        NOT NULL,
    name                       VARCHAR(255),
    surname                    VARCHAR(255),
    created_date               TIMESTAMP,
    current_fee_flat           DOUBLE PRECISION                        NOT NULL,
    current_fee_percentage     DOUBLE PRECISION                        NOT NULL,
    level                      INT                                     NOT NULL,
    role                       VARCHAR(255),
    is_account_expired         BOOLEAN                                 NOT NULL,
    is_locked                  BOOLEAN                                 NOT NULL,
    is_credentials_non_expired BOOLEAN                                 NOT NULL,
    is_enabled                 BOOLEAN                                 NOT NULL,
    previously_used_passwords  VARCHAR(255),
    profile_picture_id         BIGINT,
    is_phone_number_verified   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-21
CREATE TABLE verification_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    user_id     BIGINT,
    expiry_date TIMESTAMP,
    CONSTRAINT pk_verificationtoken PRIMARY KEY (id)
);

-- changeset michaltu:1715314131181-25
ALTER TABLE report
    ADD CONSTRAINT uc_report_reported_by UNIQUE (reported_by_id);

-- changeset michaltu:1715314131181-26
ALTER TABLE report
    ADD CONSTRAINT uc_report_reported_user UNIQUE (reported_user_id);

-- changeset michaltu:1715314131181-27
ALTER TABLE top_up
    ADD CONSTRAINT uc_topup_user_entity UNIQUE (user_entity_id);

-- changeset michaltu:1715314131181-34
ALTER TABLE listing
    ADD CONSTRAINT FK_LISTING_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

-- changeset michaltu:1715314131181-35
ALTER TABLE listing
    ADD CONSTRAINT FK_LISTING_ON_USER_ENTITY FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset michaltu:1715314131181-36
ALTER TABLE photo
    ADD CONSTRAINT FK_PHOTO_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

-- changeset michaltu:1715314131181-37
ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_RATING_GIVER FOREIGN KEY (rating_giver_id) REFERENCES user_entity (id);

-- changeset michaltu:1715314131181-38
ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_RATING_RECEIVER FOREIGN KEY (rating_receiver_id) REFERENCES user_entity (id);

-- changeset michaltu:1715314131181-39
ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_REPORTED_BY FOREIGN KEY (reported_by_id) REFERENCES user_entity (id);

-- changeset michaltu:1715314131181-40
ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_REPORTED_USER FOREIGN KEY (reported_user_id) REFERENCES user_entity (id);

-- changeset michaltu:1715314131181-41
ALTER TABLE top_up
    ADD CONSTRAINT FK_TOPUP_ON_USER_ENTITY FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset michaltu:1715314131181-42
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER_ENTITY1 FOREIGN KEY (user_entity1_id) REFERENCES user_entity (id);

-- changeset michaltu:1715314131181-43
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER_ENTITY2 FOREIGN KEY (user_entity2_id) REFERENCES user_entity (id);

-- changeset michaltu:1715314131181-44
ALTER TABLE user_entity
    ADD CONSTRAINT FK_USERENTITY_ON_PROFILE_PICTURE FOREIGN KEY (profile_picture_id) REFERENCES photo (id);

-- changeset michaltu:1715314131181-45
ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFICATIONTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);