-- liquibase formatted sql

-- changeset micha:1716550915877-1
CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

-- changeset micha:1716550915877-2
CREATE TABLE category_listings
(
    category_id BIGINT NOT NULL,
    listing_id  BIGINT NOT NULL,
    CONSTRAINT pk_category_listings PRIMARY KEY (listing_id)
);

-- changeset micha:1716550915877-3
CREATE TABLE game
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_game PRIMARY KEY (id)
);

-- changeset micha:1716550915877-4
CREATE TABLE game_categories
(
    category_id BIGINT NOT NULL,
    game_id     BIGINT NOT NULL,
    CONSTRAINT pk_game_categories PRIMARY KEY (category_id)
);

-- changeset micha:1716550915877-5
CREATE TABLE listing
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_entity_id BIGINT,
    created_date   TIMESTAMP,
    price          DOUBLE PRECISION                        NOT NULL,
    description    VARCHAR(255),
    title          VARCHAR(255),
    is_for_trade   BOOLEAN                                 NOT NULL,
    is_for_sale    BOOLEAN                                 NOT NULL,
    is_negotiable  BOOLEAN                                 NOT NULL,
    amount         INT                                     NOT NULL,
    is_quick_buy   BOOLEAN                                 NOT NULL,
    views          INT                                     NOT NULL,
    is_promoted    BOOLEAN                                 NOT NULL,
    url            VARCHAR(255),
    CONSTRAINT pk_listing PRIMARY KEY (id)
);

-- changeset micha:1716550915877-6
CREATE TABLE listing_categories
(
    category_id BIGINT NOT NULL,
    photo_id    BIGINT NOT NULL
);

-- changeset micha:1716550915877-7
CREATE TABLE listing_photos
(
    listing_id BIGINT NOT NULL,
    photo_id   BIGINT NOT NULL
);

-- changeset micha:1716550915877-8
CREATE TABLE photo
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_path VARCHAR(255),
    name      VARCHAR(255),
    CONSTRAINT pk_photo PRIMARY KEY (id)
);

-- changeset micha:1716550915877-9
CREATE TABLE rating
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating             INT                                     NOT NULL,
    opinion_message    VARCHAR(255),
    rating_giver_id    BIGINT,
    rating_receiver_id BIGINT,
    CONSTRAINT pk_rating PRIMARY KEY (id)
);

-- changeset micha:1716550915877-10
CREATE TABLE refresh_token
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token        VARCHAR(255),
    created_date TIMESTAMP,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

-- changeset micha:1716550915877-11
CREATE TABLE report
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reported_by_id   BIGINT                                  NOT NULL,
    reported_user_id BIGINT                                  NOT NULL,
    message          VARCHAR(255),
    cause            VARCHAR(255),
    CONSTRAINT pk_report PRIMARY KEY (id)
);

-- changeset micha:1716550915877-12
CREATE TABLE top_up
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date           TIMESTAMP,
    user_entity_id BIGINT                                  NOT NULL,
    amount         DOUBLE PRECISION                        NOT NULL,
    payment_option VARCHAR(255),
    CONSTRAINT pk_topup PRIMARY KEY (id)
);

-- changeset micha:1716550915877-13
CREATE TABLE transaction
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_entity1_id         BIGINT,
    user_entity2_id         BIGINT,
    date                    TIMESTAMP,
    is_trade                BOOLEAN                                 NOT NULL,
    is_monetary_transaction BOOLEAN                                 NOT NULL,
    is_user_entity1bot      BOOLEAN                                 NOT NULL,
    is_user_entity2bot      BOOLEAN                                 NOT NULL,
    chat                    BLOB,
    payment_used            VARCHAR(255),
    transaction_status      VARCHAR(255),
    listing_id              BIGINT,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

-- changeset micha:1716550915877-14
CREATE TABLE user_entity
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                   VARCHAR(255),
    email                      VARCHAR(255),
    password                   VARCHAR(255),
    phone_number               VARCHAR(255),
    balance                    DOUBLE PRECISION                        NOT NULL,
    name                       VARCHAR(255),
    surname                    VARCHAR(255),
    created_date               TIMESTAMP,
    current_fee_flat           DOUBLE PRECISION                        NOT NULL,
    current_fee_percentage     DOUBLE PRECISION                        NOT NULL,
    level                      INT                                     NOT NULL,
    role                       VARCHAR(255),
    is_account_expired         BOOLEAN                                 NOT NULL,
    is_locked                  BOOLEAN                                 NOT NULL,
    is_credentials_non_expired BOOLEAN                                 NOT NULL,
    is_enabled                 BOOLEAN                                 NOT NULL,
    previously_used_passwords  VARCHAR(255),
    profile_picture_id         BIGINT,
    is_phone_number_verified   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

-- changeset micha:1716550915877-15
CREATE TABLE user_entity_ratings_received
(
    user_entity_id      BIGINT NOT NULL,
    ratings_received_id BIGINT NOT NULL
);

-- changeset micha:1716550915877-16
CREATE TABLE user_entity_reports_received
(
    user_entity_id      BIGINT NOT NULL,
    reports_received_id BIGINT NOT NULL
);

-- changeset micha:1716550915877-17
CREATE TABLE user_entity_top_ups
(
    user_entity_id BIGINT NOT NULL,
    top_ups_id     BIGINT NOT NULL
);

-- changeset micha:1716550915877-18
CREATE TABLE user_entity_transactions
(
    user_entity_id  BIGINT NOT NULL,
    transactions_id BIGINT NOT NULL
);

-- changeset micha:1716550915877-19
CREATE TABLE verification_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    user_id     BIGINT,
    expiry_date TIMESTAMP,
    CONSTRAINT pk_verificationtoken PRIMARY KEY (id)
);

-- changeset micha:1716550915877-20
ALTER TABLE listing_categories
    ADD CONSTRAINT uc_listing_categories_photo UNIQUE (photo_id);

-- changeset micha:1716550915877-21
ALTER TABLE listing_photos
    ADD CONSTRAINT uc_listing_photos_photo UNIQUE (photo_id);

-- changeset micha:1716550915877-22
ALTER TABLE report
    ADD CONSTRAINT uc_report_reported_by UNIQUE (reported_by_id);

-- changeset micha:1716550915877-23
ALTER TABLE report
    ADD CONSTRAINT uc_report_reported_user UNIQUE (reported_user_id);

-- changeset micha:1716550915877-24
ALTER TABLE top_up
    ADD CONSTRAINT uc_topup_user_entity UNIQUE (user_entity_id);

-- changeset micha:1716550915877-25
ALTER TABLE user_entity_ratings_received
    ADD CONSTRAINT uc_user_entity_ratings_received_ratingsreceived UNIQUE (ratings_received_id);

-- changeset micha:1716550915877-26
ALTER TABLE user_entity_reports_received
    ADD CONSTRAINT uc_user_entity_reports_received_reportsreceived UNIQUE (reports_received_id);

-- changeset micha:1716550915877-27
ALTER TABLE user_entity_top_ups
    ADD CONSTRAINT uc_user_entity_top_ups_topups UNIQUE (top_ups_id);

-- changeset micha:1716550915877-28
ALTER TABLE user_entity_transactions
    ADD CONSTRAINT uc_user_entity_transactions_transactions UNIQUE (transactions_id);

-- changeset micha:1716550915877-29
ALTER TABLE listing
    ADD CONSTRAINT FK_LISTING_ON_USER_ENTITY FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-30
ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_RATING_GIVER FOREIGN KEY (rating_giver_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-31
ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_RATING_RECEIVER FOREIGN KEY (rating_receiver_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-32
ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_REPORTED_BY FOREIGN KEY (reported_by_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-33
ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_REPORTED_USER FOREIGN KEY (reported_user_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-34
ALTER TABLE top_up
    ADD CONSTRAINT FK_TOPUP_ON_USER_ENTITY FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-35
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_LISTING FOREIGN KEY (listing_id) REFERENCES listing (id);

-- changeset micha:1716550915877-36
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER_ENTITY1 FOREIGN KEY (user_entity1_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-37
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_USER_ENTITY2 FOREIGN KEY (user_entity2_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-38
ALTER TABLE user_entity
    ADD CONSTRAINT FK_USERENTITY_ON_PROFILE_PICTURE FOREIGN KEY (profile_picture_id) REFERENCES photo (id);

-- changeset micha:1716550915877-39
ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFICATIONTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-40
ALTER TABLE category_listings
    ADD CONSTRAINT fk_catlis_on_category FOREIGN KEY (category_id) REFERENCES category (id);

-- changeset micha:1716550915877-41
ALTER TABLE category_listings
    ADD CONSTRAINT fk_catlis_on_listing FOREIGN KEY (listing_id) REFERENCES listing (id);

-- changeset micha:1716550915877-42
ALTER TABLE game_categories
    ADD CONSTRAINT fk_gamcat_on_category FOREIGN KEY (category_id) REFERENCES category (id);

-- changeset micha:1716550915877-43
ALTER TABLE game_categories
    ADD CONSTRAINT fk_gamcat_on_game FOREIGN KEY (game_id) REFERENCES game (id);

-- changeset micha:1716550915877-44
ALTER TABLE listing_categories
    ADD CONSTRAINT fk_liscat_on_category FOREIGN KEY (category_id) REFERENCES category (id);

-- changeset micha:1716550915877-45
ALTER TABLE listing_categories
    ADD CONSTRAINT fk_liscat_on_listing FOREIGN KEY (photo_id) REFERENCES listing (id);

-- changeset micha:1716550915877-46
ALTER TABLE listing_photos
    ADD CONSTRAINT fk_lispho_on_listing FOREIGN KEY (listing_id) REFERENCES listing (id);

-- changeset micha:1716550915877-47
ALTER TABLE listing_photos
    ADD CONSTRAINT fk_lispho_on_photo FOREIGN KEY (photo_id) REFERENCES photo (id);

-- changeset micha:1716550915877-48
ALTER TABLE user_entity_ratings_received
    ADD CONSTRAINT fk_useentratrec_on_rating FOREIGN KEY (ratings_received_id) REFERENCES rating (id);

-- changeset micha:1716550915877-49
ALTER TABLE user_entity_ratings_received
    ADD CONSTRAINT fk_useentratrec_on_user_entity FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-50
ALTER TABLE user_entity_reports_received
    ADD CONSTRAINT fk_useentreprec_on_report FOREIGN KEY (reports_received_id) REFERENCES report (id);

-- changeset micha:1716550915877-51
ALTER TABLE user_entity_reports_received
    ADD CONSTRAINT fk_useentreprec_on_user_entity FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-52
ALTER TABLE user_entity_top_ups
    ADD CONSTRAINT fk_useenttopups_on_top_up FOREIGN KEY (top_ups_id) REFERENCES top_up (id);

-- changeset micha:1716550915877-53
ALTER TABLE user_entity_top_ups
    ADD CONSTRAINT fk_useenttopups_on_user_entity FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

-- changeset micha:1716550915877-54
ALTER TABLE user_entity_transactions
    ADD CONSTRAINT fk_useenttra_on_transaction FOREIGN KEY (transactions_id) REFERENCES transaction (id);

-- changeset micha:1716550915877-55
ALTER TABLE user_entity_transactions
    ADD CONSTRAINT fk_useenttra_on_user_entity FOREIGN KEY (user_entity_id) REFERENCES user_entity (id);

